spring:
  main:
    allow-bean-definition-overriding: 'true'
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8080/auth/realms/exactool}
  cloud:
    vault:
      enabled: false
  profiles:
    include: default
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/exactool-db}
    username: ${POSTGRES_USERNAME:admin}
    password: ${POSTGRES_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
keycloak:
  realm: ${KEYCLOAK_REALM:exactool}
  clientId: ${KEYCLOAK_CLIENT_ID:exactool}
  clientSecret: ${KEYCLOAK_SECRET:HnnDVG6Dk2mKmCP5flSLpK3Zp6Xq8RY2}
  host: ${KEYCLOAK_HOST:localhost}
  port: ${KEYCLOAK_PORT:8080}
  admin-username: ${KEYCLOAK_ADMIN_USERNAME:admin@gmail.com}
  admin-password: ${KEYCLOAK_ADMIN_PASSWORD:admin}
server:
  port: 8002

cors:
  allowed-origins: ${CORS_ORIGINS:http://localhost:4200}



